PlacementTracking/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stu/', include('student_register.urls')),
    path('tpo/', include('tpo_app.urls')),
]

tpo_app/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('login/',views.tpo_login_view,name='tpo_login'),
    path('logout/',views.tpo_logout_view,name='tpo_logout'),
    path('allstu/',views.all_students_view,name='allstu'),
    path('stufullprof/',views.student_full_profile_view,name='stu_full_prof'),
    path('newjob/',views.post_new_job_view,name='new_job'),
    path('updatejob/<int:id>',views.update_job_view,name='update_job'),
    path('deletejob/<int:id>',views.delete_job_view,name='delete_job'),
    path('vis/',views.visualize,name='visualize'),
]

student_register/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    rn = models.CharField(max_length=15)
    div = models.CharField(max_length=10)
    name = models.CharField(max_length=100)
    branch = models.CharField(max_length=30)
    mobile = models.CharField(max_length=13)
    email = models.CharField(max_length=100)
    sscm = models.DecimalField(max_digits=6, decimal_places=4)
    hscm = models.DecimalField(max_digits=6, decimal_places=4)
    fe_cgpa = models.DecimalField(max_digits=6, decimal_places=4)
    se_cgpa = models.DecimalField(max_digits=6, decimal_places=4)
    te_cgpa = models.DecimalField(max_digits=6, decimal_places=4)

    def __str__(self):
        return self.name

class StudentProfile(models.Model):
    clg_email = models.EmailField()
    fname = models.CharField(max_length=25)
    mname = models.CharField(max_length=25)
    lname = models.CharField(max_length=25)
    clg = models.CharField(max_length=50)
    prn = models.CharField(max_length=40)
    branch = models.CharField(max_length=40)
    dob = models.DateField()
    gender = models.CharField(max_length=20)
    native_place = models.CharField(max_length=50)
    mother_tounge = models.CharField(max_length=50)
    other_lang = models.CharField(max_length=50)
    mono1 = models.CharField(max_length=20)
    mono2 = models.CharField(max_length=20)
    parent_mono1 = models.CharField(max_length=20)
    parent_mono2 = models.CharField(max_length=20)
    personal_email = models.EmailField()
    parent_email = models.EmailField()
    xth_board = models.CharField(max_length=50)
    xth_passing_yr = models.IntegerField()
    xth_marks_obtained = models.IntegerField()
    xth_marks_outoff = models.IntegerField()
    xth_percentage = models.FloatField()
    xiith_board = models.CharField(max_length=50)
    xiith_passing_yr = models.IntegerField()
    xiith_marks_obtained = models.IntegerField()
    xiith_marks_outoff = models.IntegerField()
    xiith_percentage = models.FloatField()
    diploma_clg = models.CharField(max_length=50)
    diploma_passing_yr = models.IntegerField()
    diploma_marks_obtained = models.IntegerField()
    diploma_marks_outoff = models.IntegerField()
    diploma_percentage = models.FloatField()
    fe1_tot_credits = models.IntegerField()
    fe1_tot_credits_obtained = models.IntegerField()
    fe1_cgpa = models.FloatField()
    fe2_tot_credits = models.IntegerField()
    fe2_tot_credits_obtained = models.IntegerField()
    fe2_cgpa = models.FloatField()
    se1_tot_credits = models.IntegerField()
    se1_tot_credits_obtained = models.IntegerField()
    se1_cgpa = models.FloatField()
    se2_tot_credits = models.IntegerField()
    se2_tot_credits_obtained = models.IntegerField()
    se2_cgpa = models.FloatField()
    te1_tot_credits = models.IntegerField()
    te1_tot_credits_obtained = models.IntegerField()
    te1_cgpa = models.FloatField()
    te2_tot_credits = models.IntegerField()
    te2_tot_credits_obtained = models.IntegerField()
    te2_cgpa = models.FloatField()
    be1_tot_credits = models.IntegerField()
    be1_tot_credits_obtained = models.IntegerField()
    be1_cgpa = models.FloatField()
    be2_tot_credits = models.IntegerField()
    be2_tot_credits_obtained = models.IntegerField()
    be2_cgpa = models.FloatField()
    engg_cgpa = models.FloatField()
    no_of_dead_kt = models.IntegerField()
    no_of_live_kt = models.IntegerField()
    no_of_yd_engg = models.IntegerField()
    no_of_yd_diploma = models.IntegerField()
    no_of_yg = models.IntegerField()
    plan_after_engg = models.CharField(max_length=50)
    te_mini_proj_company = models.CharField(max_length=50)
    te_mini_proj_title = models.CharField(max_length=50)
    certification1 = models.CharField(max_length=50)
    certification2 = models.CharField(max_length=50)
    AddOnCourse1 = models.CharField(max_length=50)
    AddOnCourse2 = models.CharField(max_length=50)
    aadhar_no = models.CharField(max_length=20)
    placed = models.BooleanField(default=False)

    # def __str__(self):
    #     return self.clg_email

tpo_app/models.py
from django.db import models

# Create your models here.
class Jobs(models.Model):
    company = models.CharField(max_length=50)
    job_pos = models.CharField(max_length=50)
    job_loc = models.CharField(max_length=50)
    ctc_offered = models.FloatField()
    service_agg = models.IntegerField()
    date_of_joining = models.CharField(max_length=50)
    skills_req = models.CharField(max_length=500)
    selection_proc = models.CharField(max_length=500)
    date_of_campus = models.CharField(max_length=50)
    campus_venue = models.CharField(max_length=50)
    age = models.IntegerField()
    passing_yr = models.IntegerField()
    xth_percentage = models.FloatField()
    xiith_percentage = models.FloatField()
    diploma_percentage = models.FloatField()
    engg_cgpa = models.FloatField()
    no_of_dead_kt = models.IntegerField()
    no_of_live_kt = models.IntegerField()
    no_of_yg = models.IntegerField()
    reg_link = models.URLField()

tpo_app/forms.py
from .models import Jobs
from django import forms

class JobsModelForm(forms.ModelForm):
    class Meta:
        model = Jobs
        fields = '__all__'
        labels = {
            'company':'Name of the Organization',
            'job_pos': 'Job Position',
            'job_loc': 'Job Location',
            'ctc_offered':'CTC Offered',
            'service_agg':'ServiceAggrementInYrs',
            'date_of_joining':'Joining Date',
            'skills_req':'Skills Required',
            'selection_proc':'Selection Procedure',
            'date_of_campus':'Campus Date',
            'campus_venue':'campus Venue',
            'age':'Maximum Age',
            'passing_yr':'Passing Year',
            'xth_percentage':'Min. xth_percentage',
            'xiith_percentage':'Min. xiith_percentage',
            'diploma_percentage':'Min. diploma_percentage',
            'engg_cgpa':'Min. engg_cgpa'

        }

tpo_app/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
import datetime

# Create your views here.
from student_register.models import StudentProfile
from .forms import JobsModelForm
from tpo_app.models import Jobs


def tpo_login_view(request):
    dt = datetime.datetime.now()
    if request.method == "GET":
        print("GET request method for tpo_login page")
    else:
        print("POST request method for tpo_login page")
        un = request.POST['un']
        pw = request.POST['pw']
        print(un)
        if un == 'tpo':
            user = authenticate(username=un, password=pw)
            if user is not None:
                print('Valid user, logging in')
                login(request, user)
                # return redirect('allstudents')
                return redirect('alljobs')
            else:
                print('Invalid Credentials')
                messages.error(request, 'Invalid Credentials')
        else:
            print('Username is tpo redirecting to student login')
            return redirect('stulogin')

    context = {"dt": dt}
    template_name = "tpo_app/tpoLogin.html"
    return render(request, template_name, context)
    return HttpResponse(f"{un} you are Logged In!")

def tpo_logout_view(request):
    logout(request)
    return redirect('tpo_login')

def all_students_view(request):
    students = StudentProfile.objects.all()
    context = {'students':students}
    template_name = "tpo_app/allStudents.html"
    return render(request, template_name, context)

def student_full_profile_view(request):
    student = StudentProfile.objects.get(prn='71717219J')
    di = student.__dict__
    di.pop('_state')
    context = {'stu':di}
    template_name = "tpo_app/studentFullProfile.html"
    return  render(request,template_name,context)

'''
@login_required(login_url='tpo_login')
def post_new_job(request):
    # context = {}
    # template_name = "tpo_app/newJob.html"
    # return render(request,template_name,context)
    if request.method == "GET":
        print("GET req for post_new_job, opening tpo_app/newJob.html")
        # print(request.GET)
        context = {}
        template_name = "tpo_app/newJob.html"
        return render(request,template_name,context)
    if request.method == "POST":
        print("POST req for post_new_job",request.POST)
        print('Saving the student profile data into database....')
        j = Jobs()
        j.company = request.POST['company']
        j.reg_link = request.POST['reg_link']
        j.date_of_campus = request.POST['date_of_campus']
        j.campus_venue = request.POST['campus_venue']
        j.job_loc = request.POST['job_loc']
        j.job_pos = request.POST['job_pos']
        j.ctc_offered = request.POST['ctc_offered']
        j.service_agg = request.POST['service_agg']
        j.skills_req = request.POST['skills_req']
        j.selection_proc = request.POST['selection_proc']
        j.age = request.POST['age']
        j.passing_yr = request.POST['passing_yr']
        j.xth_percentage = request.POST['xth_percentage']
        j.xiith_percentage = request.POST['xiith_percentage']
        j.diploma_percentage = request.POST['diploma_percentage']
        j.engg_cgpa = request.POST['engg_cgpa']
        j.no_of_dead_kt = request.POST['no_of_dead_kt']
        j.no_of_live_kt = request.POST['no_of_live_kt']
        j.no_of_yg = request.POST['no_of_yg']
        j.date_of_joining = request.POST['date_of_joining']
        j.save()
        print("New job added in the database succesfully..")
        # return HttpResponse("Done")
        return redirect('alljobs')
'''
def post_new_job_view(request):
    if request.method == 'GET':
        form = JobsModelForm()
        context = {'form':form}
        template_name = "tpo_app/newJob1.html"
        return render(request,template_name,context)
    elif request.method == 'POST':
        form = JobsModelForm(request.POST)
        if form.is_valid():
            form.save()
            print("New job added in the database succesfully..")
            # return HttpResponse("Done")
            return redirect('alljobs')

def update_job_view(request,id):
    job_obj = Jobs.objects.get(id=id)
    if request.method == 'GET':
        form = JobsModelForm(instance=job_obj)
        context = {'form': form}
        template_name = "tpo_app/newJob1.html"
        return render(request, template_name, context)
    elif request.method == 'POST':
        form = JobsModelForm(request.POST, instance=job_obj)
        if form.is_valid():
            form.save()
            return redirect('alljobs')

def delete_job_view(request,id):
    job_obj = Jobs.objects.get(id=id)
    job_obj.delete()
    return redirect('alljobs')


def visualize(request):
    # import pandas as pd
    # import matplotlib.pyplot as plt
    #
    # s = pd.Series([1, 2, 3])
    # fig, ax = plt.subplots()
    # s.plot.bar()
    # fig.savefig('static/images/my_plot1.png')
    cnt = 0
    import pandas as pd
    import matplotlib.pyplot as plt

    s = pd.Series([1, 2, 3])
    fig, ax = plt.subplots()
    s.plot.bar()
    # img = 'static/images/my_plot'+str(cnt)+'.png'
    # print(img)
    fig.savefig('static/images/my_plot3.png')

    feimg = 'images/my_plot'+str(cnt)+'.png'
    print(feimg)
    context = {'feimg':feimg}
    template_name = "tpo_app/visualize.html"
    cnt += 1
    return render(request,template_name,context)

templates/tpo_app/allStudents.html
{% extends "student_register/layout.html" %}

    {% block title %}
        <title>All Students</title>
    {% endblock %}

    {% block css %}
        <style>
            #cssTable th,td
            {
                text-align: center;
                vertical-align: middle;

            }
        </style>
    {% endblock %}


    {% block body %}
        <div class="limiter">
            <div class="container-login100" style="background-image: url('/static/images/mmcoen.jpg');">
                <div class="wrap-login100" style="width:100%;">

                    <span class="login100-form-title p-b-34 p-t-27">
                            All Student Profiles
                    </span>

                    <table border="1px" width="100%" id="cssTable">
                        <thead align="center">
                            <th>PRN</th>
                            <th>Name</th>
                            <th>Branch</th>
                            <th>College Email</th>
                            <th>Mobile Number</th>
                        </thead>
                        {% for stu in students %}
                            <tr>
                                <td>{{ stu.prn }}</td>
                                <td>{{ stu.fname }} {{ stu.lname }}</td>
                                <td>{{ stu.branch }}</td>
                                <td>{{ stu.clg_email }}</td>
                                <td>{{ stu.mono1 }}</td>
                                <td>
                                    <div class="wrap-input100">
                                        <select name="status" class="input100">
                                            <option value="placed">Placed</option>
                                            <option value="not_placed">Not Placed</option>
                                        </select>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>

                </div>
		    </div>
	    </div>


	<div id="dropDownSelect1"></div>
    {% endblock %}

templates/tpo_app/newJob.html
{% extends "student_register/layout.html" %}

    {% block title %}
        <title>Post New Job</title>
    {% endblock %}

    {% block css %}
        <style>
             table.center
             {
                margin-left:auto;
                margin-right:auto;
             }
        </style>
    {% endblock %}

    {% block body %}
        <div class="limiter">
            <div class="container-login100" style="background-image: url('/static/images/mmcoen.jpg');">
                <div class="wrap-login100" style="width: 800px;">
                    <form class="login100-form validate-form" method="post">
                        {% csrf_token %}
                        <span class="login100-form-title p-b-34 p-t-27">
                            Post New Job
                        </span>
{#                        <span class="login100-form-logo p-b-34 p-t-0">#}
{#                            <h4 style="text-align: center">Step 1 - Personal Details</h4>#}
                        <br>
{#                        </span>#}
                        <br>
{#                        <label for="id_fname">Fname:</label><br>#}

                        <table>
                            <tr>
                                <div class="wrap-input100 validate-input" data-validate ="Enter Valid Company Name">
                                        <input class="input100" type="text" name="company">
                                        <span class="focus-input100" style="font-size: 18px" data-placeholder="Name of the Organization" ></span>
                                </div>
                            </tr>
                            <tr>
                                <div class="wrap-input100 validate-input" data-validate ="Enter Valid Registration Link">
                                        <input class="input100" type="text" name="reg_link">
                                        <span class="focus-input100" data-placeholder="reg_link"></span>
                                </div>
                            </tr>
                        </table>
                        <table class="center">
                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Campus Date">
                                        <input class="input100" type="date" name="date_of_campus">
                                        <span class="focus-input100" data-placeholder="Campus Date"></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid campus Venue">
                                        <input class="input100" type="text" name="campus_venue">
                                        <span class="focus-input100" data-placeholder="campus Venue"></span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Job Location">
                                        <input class="input100" type="text" name="job_loc">
                                        <span class="focus-input100" style="font-size: 18px" data-placeholder="Job Location" ></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Job Position">
                                        <input class="input100" type="text" name="job_pos">
                                        <span class="focus-input100" style="font-size: 18px" data-placeholder="Job Position" ></span>
                                    </div>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid CTC Offered">
                                        <input class="input100" type="text" name="ctc_offered">
                                        <span class="focus-input100" style="font-size: 18px" data-placeholder="CTC Offered" ></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Service Aggrement in Yrs">
                                        <input class="input100" type="number" name="service_agg">
                                        <span class="focus-input100" style="font-size: 18px" data-placeholder="ServiceAggrementInYrs" ></span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Skills Required">
                                        <input class="input100" type="text" name="skills_req">
                                        <span class="focus-input100" data-placeholder="Skills Required"></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Selection Procedure">
                                        <input class="input100" type="text" name="selection_proc">
                                        <span class="focus-input100" data-placeholder="Selection Procedure"></span>
                                    </div>
                                </td>


                            </tr>




                            <tr>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Age">
                                        <input class="input100" type="number" name="age">
                                        <span class="focus-input100" data-placeholder="Max. Age"></span>
                                    </div>
                                </td>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid Passing Year">
                                        <input class="input100" type="text" name="passing_yr">
                                        <span class="focus-input100" data-placeholder="Passing Year"></span>
                                    </div>
                                </td>
                            </tr>

                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid xth_percentage">
                                        <input class="input100" type="text" name="xth_percentage">
                                        <span class="focus-input100" data-placeholder="Min. xth_percentage"></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid xiith_percentage">
                                        <input class="input100" type="text" name="xiith_percentage">
                                        <span class="focus-input100" data-placeholder="Min. xiith_percentage"></span>
                                    </div>
                                </td>

                            </tr>



                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid diploma_percentage">
                                        <input class="input100" type="text" name="diploma_percentage">
                                        <span class="focus-input100" data-placeholder="Min. diploma_percentage"></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid engg_cgpa">
                                        <input class="input100" type="text" name="engg_cgpa">
                                        <span class="focus-input100" data-placeholder="Min. engg_cgpa"></span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid no_of_dead_kt">
                                        <input class="input100" type="number" name="no_of_dead_kt">
                                        <span class="focus-input100" data-placeholder="Max. no_of_dead_kt"></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid no_of_live_kt">
                                        <input class="input100" type="number" name="no_of_live_kt">
                                        <span class="focus-input100" data-placeholder="Max. no_of_live_kt"></span>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid no_of_yg">
                                        <input class="input100" type="number" name="no_of_yg">
                                        <span class="focus-input100" data-placeholder="Max. no_of_yg"></span>
                                    </div>
                                </td>
                                <td style="padding: 0px 2px 0px 2px">
                                    <div class="wrap-input100 validate-input" data-validate ="Enter Valid date_of_joining">
                                            <input class="input100" type="date" name="date_of_joining">
                                            <span class="focus-input100" style="font-size: 18px" data-placeholder="Joining Date" ></span>
                                    </div>
                                </td>
                            </tr>
                        </table>
{#                        <br><br>#}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                        <span style=" background: springgreen; border-radius: 5px; padding: 5px 15px 5px 15px">
{#                                      <a>NEXT</a>#}
{#                                      <input type="button" value="NEXT">#}
                            <button>Post</button>
                        </span>

{##}

                        <br>



                        <br>









{#                        {{ regform }}#}
                    </form>
                </div>
		    </div>
	    </div>
    {% endblock %}

templates/tpo_app/newJob1.html
{% extends "student_register/layout.html" %}
{% load crispy_forms_tags %}

    {% block title %}
        <title>Post New Job</title>
    {% endblock %}

    {% block css %}
        <style>
             table.center
             {
                margin-left:auto;
                margin-right:auto;
             }
        </style>
    {% endblock %}

    {% block body %}
        <div class="limiter">
            <div class="container-login100" style="background-image: url('/static/images/mmcoen.jpg');">
                <div class="wrap-login100" style="width: 800px;">
                    <form class="login100-form validate-form" method="post">
                        {% csrf_token %}
                        <span class="login100-form-title p-b-34 p-t-27">
                            Post New Job
                        </span>
                        <br>
                        <br>
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-success">
                            POST
                        </button>

                    </form>
                </div>
		    </div>
	    </div>
    {% endblock %}

templates/tpo_app/studentFullProfile.html
{% extends "student_register/layout.html" %}

    {% block title %}
        <title>Student Profile</title>
    {% endblock %}

    {% block css %}
        <style>
            #cssTable th,td
            {
                text-align: center;
                vertical-align: middle;

            }
        </style>
    {% endblock %}


    {% block body %}
        <div class="limiter">
            <div class="container-login100" style="background-image: url('/static/images/mmcoen.jpg');">
                <div class="wrap-login100" style="width:100%;">

                    <span class="login100-form-title p-b-34 p-t-27">
                            Full Profile
                    </span>
                    <table class="table" border="1px" width="100%" id="cssTable">
{#                        <thead align="center">#}
{#                            <th>PRN</th>#}
{#                            <th>Name</th>#}
{#                            <th>Branch</th>#}
{#                            <th>College Email</th>#}
{#                            <th>Mobile Number</th>#}
{#                        </thead>#}
{#                        {% for stu in students %}#}
                        <thead class="thead-dark">
                            <tr>
                              <th scope="col">Parameter</th>
                              <th scope="col">Value</th>
                            </tr>
                        </thead>
                        {% for k,v in stu.items %}
                            <tr>
                                <td>{{ k }}</td>
                                <td>{{ v }}</td>
                            </tr>
{#                            {{ k }}-{{ v }}<br>#}
                        {% endfor %}
{#                            {{ stu }}#}
{#                            <tr>#}
{#                                <td>PRN Number:</td>#}
{#                                <td>{{ stu.prn }}</td>#}
{#                            </tr>#}
{#                            <tr>#}
{#                                <td>{{ stu.fname }} {{ stu.lname }}</td>#}
{#                                <td>{{ stu.branch }}</td>#}
{#                                <td>{{ stu.clg_email }}</td>#}
{#                                <td>{{ stu.mono1 }}</td>#}
{#                            </tr>#}
{#                        {% endfor %}#}
                    </table>

                </div>
		    </div>
	    </div>


	<div id="dropDownSelect1"></div>
    {% endblock %}